version: '2'
services:
    zipper:
        build: python-zipper/zipper/
        volumes:
            - ./python-zipper/zipper:/app/
        ports:
            -  8125:8000
        command: gunicorn -c zipper/gunicorn_conf.py zipper.wsgi

    rest:
        volumes: 
           - ./rest/:/app/
        ports:
           - 8124:8000

