version: '2'
services:
    zipper:
        image: guydou/zipper-python
        links: 
             - redis:redis
        environment:
            - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
            - AWS_REGION=$AWS_REGION
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        ports:
            -  8125:8000

    redis:
        image: redis

    rest:
        image: guydou/zipper-rest
        links:
            - redis:redis
        ports:
            -  8124:8000


